organism: "t/data/fixture/organism.yaml"
ontology:
   sequence: 
        file: "t/data/fixture/sofa.obo_xml"
        namespace: sequence
   relation: 
        file: "t/data/fixture/relationship.obo_xml"
        namespace: relationship
   publication: 
        file: "t/data/fixture/publication.obo_xml"
        namespace: pub_type
