organism: 
   taxon:
        file: "organism.yaml"
cv:
   sequence: 
        file: "sofa.obo_xml"
        namespace: sequence
   relation: 
        file: "relationship.obo_xml"
        namespace: relationship
   publication: 
        file: "publication.obo_xml"
        namespace: pub_type
pub:
   journal:
       file: "journal.xml"
